name: Publish

on:
  push:
    branches:
      - master

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Generate release
        run: yarn release
      - name: Publish
        run: |
          NPM_TOKEN=${NPM_TOKEN}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
